apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: alpine-pod
    image: alpine
    imagePullPolicy: Never
    command: ["watch", "-n", "10", "wget", "localhost"]
