apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      nodeName: kind-worker2
      containers:
      - name: my-nginx
        image: nginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80



