apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      nodeName: minikube-m02
      containers:
      - name: my-nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80



