apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: container-1
    image: nginx
    imagePullPolicy: Never
    ports:
    - containerPort: 80  
  - name: container-2
    image: alpine
    imagePullPolicy: Never
    command: ["watch", "-n", "10", "wget", "localhost"]
